<a href="https://colab.research.google.com/github/PasinduDil/ML-exercise/blob/main/Daniel_Bouke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors

In [1]:
#import tenserflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
#create tenser with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
reshaep=tf.constant([1,2,3,4,5,6,7,8,9],shape=(3,3))
reshaep

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [4]:
dtype=tf.constant([1,2,3,4,5,6,7,8,9,0],shape=(5,2),dtype=tf.int32)
dtype

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]], dtype=int32)>

In [5]:
mtrax=tf.constant([

                   [
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9]
                   ],
                   [
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9]
                   ]
])
mtrax.shape

TensorShape([2, 3, 9])

In [6]:
mtrax.ndim

3

In [7]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
tf.constant(a)
a.reshape(2,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
a.ndim

2

In [9]:
#create a vector
vector=tf.constant([1,2])
print(vector)
vector.ndim

tf.Tensor([1 2], shape=(2,), dtype=int32)


1

In [10]:
#create a matrix
matrix=tf.constant([[1,2],[3,4]])
print(matrix)
matrix.ndim

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


2

In [11]:
#create another matrix
another_matrix=tf.constant([[3.,5.,7.],[4.,6.,8.]],dtype=tf.float32,shape=(6,1))
print(another_matrix)
another_matrix.ndim

tf.Tensor(
[[3.]
 [5.]
 [7.]
 [4.]
 [6.]
 [8.]], shape=(6, 1), dtype=float32)


2

In [12]:
#create a tensor
tensor=tf.constant([
[
                     [1,2,3,4,5],
                     [1,2,3,4,5],
                     [1,2,3,4,5]
],

[
                     [1,2,3,4,5],
                     [1,2,3,4,5],
                     [1,2,3,4,5]
],

[
                     [1,2,3,4,5],
                     [1,2,3,4,5],
                     [1,2,3,4,5]
]])
print(tensor)
tensor.ndim

tf.Tensor(
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]], shape=(3, 3, 5), dtype=int32)


3

# Creating Tensors with tf.Variable

In [13]:
# create the same variable with tf.veriable ()as above
changeable_tensor=tf.Variable([10,10])
unchangeable_tensor=tf.constant([10,10])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [15]:
changeable_tensor[1].assign(111)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([111, 111], dtype=int32)>

## creating random tensor

In [24]:
random_1=tf.random.Generator.from_seed(1)
random_1=random_1.normal(shape=(2,3,2))


random_2=tf.random.Generator.from_seed(1)
random_2=random_2.normal(shape=(2,3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[ 0.43842274, -0.53439844],
         [-0.07710262,  1.5658046 ],
         [-0.1012345 , -0.2744976 ]],
 
        [[ 1.4204658 ,  1.2609464 ],
         [-0.43640924, -1.9633987 ],
         [-0.06452483, -1.056841  ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[ 0.43842274, -0.53439844],
         [-0.07710262,  1.5658046 ],
         [-0.1012345 , -0.2744976 ]],
 
        [[ 1.4204658 ,  1.2609464 ],
         [-0.43640924, -1.9633987 ],
         [-0.06452483, -1.056841  ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 2), dtype=bool, numpy=
 array([[[ True,  True],
         [ True,  True],
         [ True,  True]],
 
        [[ True,  True],
         [ True,  True],
         [ True,  True]]])>)

## Shuffle the order of elements in a tensors

In [28]:
tf.random.set_seed(42)
tf.random.shuffle(
    [1,2,3,4,5,6,7,8,9], seed=42)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([4, 1, 7, 6, 8, 3, 9, 2, 5], dtype=int32)>

## Outher ways to make tensors

In [32]:
# create a tensor of all ones
tf.ones(shape=(10,10),dtype=tf.int32)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [33]:
#create a all zeroes
tf.zeros(shape=(4,5),dtype=tf.int32)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [34]:
# the main difference between Numpy and tensorflow tensors is that can be run on a GPU and TPU

In [35]:
import numpy as np
number_A=np.arange(1,25,dtype=np.int32)
number_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [42]:
A=tf.constant(number_A,shape=(8,3))
B=tf.constant(number_A)
A,B


(<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [44]:
print(A.ndim)
print(B.ndim)


2
1


# Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [52]:
#Create a rank 4 tensor(4 Dimensions)
rank_4_tensor=tf.zeros(shape=(2,3,4,5),dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [53]:
tf.shape(rank_4_tensor),rank_4_tensor.ndim,tf.size(rank_4_tensor),rank_4_tensor.dtype

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>,
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.int32)

In [54]:
# Get various attributes of our tensor
print("Datatype of even element :",rank_4_tensor.dtype,"\n")
print("Number of dimennsions (rank)",rank_4_tensor.ndim,"\n")
print("Shape of tensor",rank_4_tensor.shape,"\n")
print("Element along of 0 axis ",rank_4_tensor[0],"\n")
print("Element along of last axis :",rank_4_tensor[-1],"\n")
print("Total number of element in our tensor :",tf.size(rank_4_tensor),"\n")


Datatype of even element : <dtype: 'int32'> 

Number of dimennsions (rank) 4 

Shape of tensor (2, 3, 4, 5) 

Element along of 0 axis  tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(3, 4, 5), dtype=int32) 

Element along of last axis : tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(3, 4, 5), dtype=int32) 

Total number of element in our tensor : tf.Tensor(120, shape=(), dtype=int32) 



In [57]:
# Get the first 2 element of each diagram
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [58]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>

In [72]:
a=np.arange(1,25,dtype=np.int32)
some_list=tf.constant(a,shape=(2,4,3))
some_list

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [73]:
some_list[:,:,-1]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]], dtype=int32)>