<a href="https://colab.research.google.com/github/PasinduDil/ML-exercise/blob/main/Daniel_Bouke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors

In [1]:
#import tenserflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
#create tenser with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
reshaep=tf.constant([1,2,3,4,5,6,7,8,9],shape=(3,3))
reshaep

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [7]:
dtype=tf.constant([1,2,3,4,5,6,7,8,9,0],shape=(5,2),dtype=tf.int32)
dtype

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]], dtype=int32)>

In [12]:
mtrax=tf.constant([

                   [
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9]
                   ],
                   [
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9],
                       [1,2,3,4,5,6,7,8,9]
                   ]
])
mtrax.shape

TensorShape([2, 3, 9])

In [26]:
mtrax.ndim

3

In [24]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
tf.constant(a)
a.reshape(2,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
a.ndim

2

In [32]:
#create a vector
vector=tf.constant([1,2])
print(vector)
vector.ndim

tf.Tensor([1 2], shape=(2,), dtype=int32)


1

In [33]:
#create a matrix
matrix=tf.constant([[1,2],[3,4]])
print(matrix)
matrix.ndim

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


2

In [40]:
#create another matrix
another_matrix=tf.constant([[3.,5.,7.],[4.,6.,8.]],dtype=tf.float32,shape=(6,1))
print(another_matrix)
another_matrix.ndim

tf.Tensor(
[[3.]
 [5.]
 [7.]
 [4.]
 [6.]
 [8.]], shape=(6, 1), dtype=float32)


2